apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: orders-messaging-external-secret
  namespace: retail-store-ns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: orders-messaging-secret    # The K8s Secret name to be created
    creationPolicy: Owner
    deletionPolicy: "Retain"
  data:
  - secretKey: RABBITMQ_DEFAULT_PASS    # Key in K8s Secret
    remoteRef:
      key: retail-store/orders/messaging/secret                       # AWS Secret Name
      property: RABBITMQ_DEFAULT_PASS   # Key in AWS Secret
      decodingStrategy: None

  - secretKey: RABBITMQ_DEFAULT_USER    # Key in K8s Secret
    remoteRef:
      key: retail-store/orders/messaging/secret                       # AWS Secret Name
      property: RABBITMQ_DEFAULT_USER   # Key in AWS Secret
      decodingStrategy: None # can be None, Base64, Base64URL or Auto