apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout-configmap
  namespace: retail-store-ns
data:
  PORT: "8080"
  RETAIL_CHECKOUT_ENDPOINTS_ORDERS: "http://orders-svc:8080"
  RETAIL_CHECKOUT_PERSISTENCE_PROVIDER: "redis"
  RETAIL_CHECKOUT_PERSISTENCE_REDIS_URL: "redis://checkout-redis-svc:6379"
  RETAIL_CHECKOUT_PERSISTENCE_REDIS_READER_URL: "redis://checkout-redis-svc:6379"