apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-configmap
  namespace: retail-store-ns
data:
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "prod"
  RETAIL_ORDERS_PERSISTENCE_PROVIDER: "postgres"
  RETAIL_ORDERS_PERSISTENCE_ENDPOINT: "orders-db-svc:5432"
  RETAIL_ORDERS_PERSISTENCE_NAME: "orders-database"
  RETAIL_ORDERS_MESSAGING_PROVIDER: "rabbitmq"
  RETAIL_ORDERS_MESSAGING_RABBITMQ_ADDRESSES: "orders-mq-svc:5672"
  SPRING_RABBITMQ_HOST: "orders-mq-svc"
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: "${RETAIL_ORDERS_MESSAGING_RABBITMQ_USERNAME}" 
  SPRING_RABBITMQ_PASSWORD: "${RETAIL_ORDERS_MESSAGING_RABBITMQ_PASSWORD}"