apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: orders-backend-external-secret
  namespace: retail-store-ns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: orders-backend-secret           # The K8s Secret name to be created
    creationPolicy: Owner
    deletionPolicy: "Retain"
  data:
  - secretKey: RETAIL_ORDERS_PERSISTENCE_USERNAME    # Key in K8s Secret
    remoteRef:
      key: retail-store/orders/backend/secret                       # AWS Secret Name
      property: RETAIL_ORDERS_PERSISTENCE_USERNAME   # Key in AWS Secret

  - secretKey: RETAIL_ORDERS_PERSISTENCE_PASSWORD    # Key in K8s Secret
    remoteRef:
      key: retail-store/orders/backend/secret                       # AWS Secret Name
      property: RETAIL_ORDERS_PERSISTENCE_PASSWORD   # Key in AWS Secret

  - secretKey: RETAIL_ORDERS_MESSAGING_RABBITMQ_USERNAME    # Key in K8s Secret
    remoteRef:
      key: retail-store/orders/backend/secret                       # AWS Secret Name
      property: RETAIL_ORDERS_MESSAGING_RABBITMQ_USERNAME   # Key in AWS Secret

  - secretKey: RETAIL_ORDERS_MESSAGING_RABBITMQ_PASSWORD    # Key in K8s Secret
    remoteRef:
      key: retail-store/orders/backend/secret                       # AWS Secret Name
      property: RETAIL_ORDERS_MESSAGING_RABBITMQ_PASSWORD   # Key in AWS Secret
  
