apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-configmap
  namespace: retail-store-ns
data:
  SERVER_PORT: "8080"
  RETAIL_CART_PERSISTENCE_PROVIDER: "dynamodb"
  RETAIL_CART_PERSISTENCE_DYNAMODB_ENDPOINT: "http://cart-db-svc:8000"
  RETAIL_CART_PERSISTENCE_DYNAMODB_CREATE_TABLE: "true"
  SPRING_PROFILES_ACTIVE: "prod"
  AWS_ACCESS_KEY_ID: "fake"
  AWS_SECRET_ACCESS_KEY: "fake"