apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: orders-database-external-secret
  namespace: retail-store-ns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: orders-database-secret    # The K8s Secret name to be created
    creationPolicy: Owner
    deletionPolicy: "Retain"
  data:
  - secretKey: POSTGRES_PASSWORD    # Key in K8s Secret
    remoteRef:
      key: retail-store/orders/database/secret                       # AWS Secret Name
      property: POSTGRES_PASSWORD   # Key in AWS Secret
      decodingStrategy: None

  - secretKey: POSTGRES_USER    # Key in K8s Secret
    remoteRef:
      key: retail-store/orders/database/secret                       # AWS Secret Name
      property: POSTGRES_USER   # Key in AWS Secret
      decodingStrategy: None # can be None, Base64, Base64URL or Auto

  - secretKey: POSTGRES_DB    # Key in K8s Secret
    remoteRef:
      key: retail-store/orders/database/secret                       # AWS Secret Name
      property: POSTGRES_DB   # Key in AWS Secret
      decodingStrategy: None    