apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: catalog-backend-external-secret
  namespace: retail-store-ns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: catalog-backend-secret           # The K8s Secret name to be created
    creationPolicy: Owner
    deletionPolicy: "Retain"
  data:
  - secretKey: RETAIL_CATALOG_PERSISTENCE_PASSWORD    # Key in K8s Secret
    remoteRef:
      key: retail-store/catalog/backend/secret                       # AWS Secret Name
      property: RETAIL_CATALOG_PERSISTENCE_PASSWORD   # Key in AWS Secret