apiVersion: v1
kind: Service
metadata:
  name: cart-db-svc
  namespace: retail-store-ns
spec:
  clusterIP: None
  ports:
  - port: 8000
    targetPort: 8000
    name: dynamodb
  selector:
    app: cart-db