apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: catalog-database-external-secret
  namespace: retail-store-ns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: catalog-database-secret           # The K8s Secret name to be created
    creationPolicy: Owner
    deletionPolicy: "Retain"
  data:
  - secretKey: MYSQL_ROOT_PASSWORD    # Key in K8s Secret
    remoteRef:
      key: retail-store/catalog/database/secret                       # AWS Secret Name
      property: MYSQL_ROOT_PASSWORD   # Key in AWS Secret
      decodingStrategy: None

  - secretKey: MYSQL_DATABASE    # Key in K8s Secret
    remoteRef:
      key: retail-store/catalog/database/secret                       # AWS Secret Name
      property: MYSQL_DATABASE   # Key in AWS Secret
      decodingStrategy: None # can be None, Base64, Base64URL or Auto

  - secretKey: MYSQL_PASSWORD    # Key in K8s Secret
    remoteRef:
      key: retail-store/catalog/database/secret                       # AWS Secret Name
      property: MYSQL_PASSWORD   # Key in AWS Secret
      decodingStrategy: None

  - secretKey: MYSQL_USER    # Key in K8s Secret
    remoteRef:
      key: retail-store/catalog/database/secret                       # AWS Secret Name
      property: MYSQL_USER   # Key in AWS Secret
      decodingStrategy: None
    