apiVersion: v1
kind: Service
metadata:
  name: catalog-db-svc
  namespace: retail-store-ns
spec:
  clusterIP: None
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  selector:
    app: catalog-db